Login:  ##登录模块
  login:  ##登录接口
    path:  /account/sLogin
    method: POST
  logout: ##退出接口
    path: /account/logout HTTP/1.1
    method: POST
    heard:  token

Shop: ##店铺模块
  update:  ##新增店铺
    path: /shopping/updatemyshop
    method: POST
  query:  ##列出店铺
    path: /shopping/myShop
    method: GET
  file_upload:  ##上传文件
    path: /file
    method: POST


